#!/usr/bin/env node

var file = process.argv[2]
if(!file){
  console.log('错误：需要输入文件名')
  process.exit(1)
}

var sh = require('shelljs')
var tempdir = 'temp_'+Date.now()
sh.rm('-rf', tempdir)
sh.mkdir(tempdir)
sh.cd(tempdir)

if(sh.exec('git clone https://github.com/uservGitHub/practice.git').code !== 0){
  sh.echo('错误：无法从git获取')
  sh.exit(2)
}
sh.cp('practice/'+file, '../'+file)
sh.cd('..')
sh.rm('-rf', tempdir)
